---
- name: User Creation
  user:
    name: chandu
    state: present
    shell: /bin/shell
- name: Give ssh access
  authorized_key:
    user: chandu
    state: present
    key: "{{ lookup('file','../../../user_ssh_keys/chandu/id_rsa.pub')}}"
  tags:
    - grant
