---
- name: revoke ssh access
  authorized_key:
    user: chandu
    state: absent
    key: "{{ lookup('file','../../../user_ssh_keys/chandu/id_rsa.pub')}}"
  tags:
    - revoke
- name: User Deletion
  user:
    name: chandu
    state: absent
   ## shell: /bin/shell
